# Generated by Django 5.2.1 on 2025-05-18 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('loss', models.DecimalField(decimal_places=4, max_digits=15)),
                ('profit_goal', models.DecimalField(decimal_places=4, max_digits=15)),
                ('lot_size', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ending_balance', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(default='EURUSD', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botcore.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('pips', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_liquidated', models.BooleanField(default=False)),
                ('liquidation_status', models.CharField(choices=[('none', 'None yet'), ('long_liquidated', 'Long liquidated'), ('short_liquidated', 'Short liquidated'), ('both_loss', 'Both positions lost'), ('both_win', 'Both positions won')], default='none', max_length=20)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='botcore.history')),
            ],
        ),
        migrations.CreateModel(
            name='Subaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('ctrader', 'cTrader'), ('mt4', 'MetaTrader 4'), ('mt5', 'MetaTrader 5'), ('other', 'Other')], default='ctrader', max_length=20)),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='subaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botcore.subaccount'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
