# Generated by Django 5.2.1 on 2025-05-21 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('loss', models.DecimalField(decimal_places=4, max_digits=15)),
                ('profit_goal', models.DecimalField(decimal_places=4, max_digits=15)),
                ('lot_size', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ending_balance', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('curr_active', models.CharField(choices=[('L', 'Long'), ('S', 'Short')], max_length=10)),
                ('starting_balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('profit_goal', models.DecimalField(decimal_places=4, max_digits=15)),
                ('ending_balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('ctrader', 'cTrader'), ('mt4', 'MetaTrader 4'), ('mt5', 'MetaTrader 5'), ('other', 'Other')], default='ctrader', max_length=20)),
                ('account_id', models.CharField(max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subaccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Segments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_balance', models.DecimalField(decimal_places=4, max_digits=15)),
                ('pair', models.CharField(default='EURUSD', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('milestone_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botcore.milestone')),
                ('subaccount_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botcore.subaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('position_type', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('pips', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('latest_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_liquidated', models.BooleanField(default=False)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('response', models.TextField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='botcore.trades')),
            ],
        ),
    ]
